stages:
  - build
  - publish

variables:
  PYPI_REPOSITORY_URL: "https://upload.pypi.org/legacy/"
  PYPI_TOKEN: $PYPI_TOKEN  # Set this in your GitLab project's CI/CD settings

.build_template: &build_template
  stage: build
  image: python:3.9
  before_script:
    - pip install maturin
    - cd file_system
  script:
    - maturin build --release --out dist --target $TARGET
  artifacts:
    paths:
      - dist/*

build:linux_x86_64:
  <<: *build_template
  variables:
    TARGET: x86_64-unknown-linux-gnu
  tags:
    - linux
    - x86_64

build:macos_x86_64:
  <<: *build_template
  variables:
    TARGET: x86_64-apple-darwin
  tags:
    - macos
    - x86_64

build:windows_x86_64:
  <<: *build_template
  variables:
    TARGET: x86_64-pc-windows-msvc
  tags:
    - windows
    - x86_64

publish:
  stage: publish
  image: python:3.9
  script:
    - pip install twine
    - twine upload --repository-url $PYPI_REPOSITORY_URL --skip-existing -u __token__ -p $PYPI_TOKEN dist/*
  only:
    - tags
  dependencies:
    - build:linux_x86_64
    - build:macos_x86_64
    - build:windows_x86_64
