[package]
name = "rustic_shell"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
thiserror = "1.0.56"
log = "0.4.20"
env_logger = "0.11.1"
file_system = { path = "../file_system" }